### PR TITLE
Overwrite files to avoid problems with duplicate files in JARs

### PR DESCRIPTION
**Pull request by bjoernQ**
This tries to tackle #67 - needs more testing

### CODE REVIEW

**Comment by rekire** [comment]
Hey Björn, how is the testing working? :-)

I'm playing a bit with ui component tests and run into the issue you are trying to fix with this PR.

**Comment by bjoernQ** [comment]
On my side the tests looked good - if you are currently running into this it would be great if you could try this branch and if it works for you, I can merge this and create a release

**Comment by eyal-lezmy** [comment]
Hey @bjoernQ,
How could we help to move this PR forward?

**Comment by bjoernQ** [comment]
> Hey @bjoernQ, How could we help to move this PR forward?

Just give it a try and let me know if it works - that's probably it

**Comment by eyal-lezmy** [comment]
I tested the patch cherry picked on top of master and it solved the `FileAlreadyExistsException` we encountered. For me it is all good.
Thanks for your reactivity!

One note on the current project configuration: I had to rename the "buildSrc" to "library" and add it to settings.gradle to publish it to maven local. Would you have another way to make it easier to test your project out of the box?

**Review by eyal-lezmy — APPROVED** [review]

**Comment by bjoernQ** [comment]
I hope I get to create a release soon

> One note on the current project configuration: I had to rename the "buildSrc" to "library" and add it to settings.gradle to publish it to maven local. Would you have another way to make it easier to test your project out of the box?

To be honest I moved to embedded Rust for quite some time and not doing any Android development since then - maybe someone else can comment on this and/or create a PR to improve that

**Comment by eyal-lezmy** [comment]
Good point. Do you really count on "buildScr" integration for your example projects?

**Pull request merged**
